repos:
  # Python linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  # TypeScript/JavaScript linting and formatting
  - repo: local
    hooks:
      - id: ultracite-fix
        name: Ultracite Format
        entry: bunx ultracite fix
        language: system
        files: \.(js|jsx|ts|tsx|json|jsonc)$
        pass_filenames: false

  # TypeScript type checking (pre-push only)
  - repo: local
    hooks:
      - id: typescript-check
        name: TypeScript Type Check
        entry: bash -c 'cd apps/chrome-extension && bunx tsc --noEmit'
        language: system
        files: \.(ts|tsx)$
        pass_filenames: false
        stages: [pre-push]

  # Build verification (pre-push only)
  - repo: local
    hooks:
      - id: build-check
        name: Build Chrome Extension
        entry: bash -c 'cd apps/chrome-extension && bun run build > /dev/null 2>&1'
        language: system
        files: ^apps/chrome-extension/
        pass_filenames: false
        stages: [pre-push]
