name: CI (Monorepo)

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.3.0"

      - name: Set up uv
        uses: astral-sh/setup-uv@v3

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            node_modules
          key: bun-${{ runner.os }}-${{ hashFiles('bun.lock') }}
          restore-keys: |
            bun-${{ runner.os }}-

      - name: Cache uv and .venv
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            .venv
          key: uv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml', 'uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-${{ matrix.python-version }}-

      - name: Install Bun dependencies
        run: bun install --frozen-lockfile

      - name: Install Python dependencies (uv workspace)
        run: uv sync --dev

      - name: Run Python tests (packages/commonforms-core)
        run: |
          cd packages/commonforms-core
          uv run -m pytest

      - name: Check code formatting
        run: bun run format:check

      - name: Lint and build Chrome extension
        run: |
          cd apps/chrome-extension
          bun run lint
          bun run build

      - name: Run Turborepo tasks
        run: bun run test
